booking-facilities/Controllers/SportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using booking_facilities.Models;
using Microsoft.AspNetCore.Authorization;
using X.PagedList;
using booking_facilities.Repositories;
using AberFitnessAuditLogger;

namespace booking_facilities.Controllers
{
    [Authorize(AuthenticationSchemes = "oidc", Policy = "Administrator")]
    public class SportsController : Controller
    {
        private readonly ISportRepository sportRepository;
        private readonly IAuditLogger auditLogger;

        public SportsController(ISportRepository sportRepository, IAuditLogger auditLogger)
        {
            this.sportRepository = sportRepository;
            this.auditLogger = auditLogger;
        }

        // GET: Sports
        public async Task<IActionResult> Index(int? page)
        {
            await auditLogger.log(GetUserId(), "Accessed Sport Index");
            var sportsQ = sportRepository.GetAllAsync().OrderBy(s => s.SportName);
            var sportsList = await sportsQ.ToListAsync();

            var pageNumber = page ?? 1; 
            var sportsPerPage = 10;

            var onePageOfSports = sportsList.ToPagedList(pageNumber, sportsPerPage); 

            ViewBag.onePageOfSports = onePageOfSports;
            return View();
        }

        // GET: Sports/Create
        public async Task<IActionResult> Create()
        {
            await auditLogger.log(GetUserId(), "Accessed Create Sport");
            return View();
        }

        // POST: Sports/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SportId,SportName")] Sport sport)
        {
            if (sportRepository.DoesSportExist(sport.SportName))
            {
                ModelState.AddModelError("SportName","Sport already exists. Please enter another sport.");
            }

            if (ModelState.IsValid)
            {
                sport = await sportRepository.AddAsync(sport);
                await auditLogger.log(GetUserId(), $"Created Sport {sport.SportName}");
                return RedirectToAction(nameof(Index));
            }
            return View(sport);
        }

        // GET: Sports/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            await auditLogger.log(GetUserId(), $"Accessed Edit Sport {id}");
            var sport = await sportRepository.GetByIdAsync(id.Value);
            if (sport == null)
            {
                return NotFound();
            }
            return View(sport);
        }

        // POST: Sports/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SportId,SportName")] Sport sport)
        {
            if (id != sport.SportId)
            {
                return NotFound();
            }


            if (sportRepository.DoesSportExist(sport.SportName))
            {
                ModelState.AddModelError("SportName", "Sport already exists. Please enter another sport.");
            }
            else if(ModelState.IsValid)
            {
                try
                {
                    await sportRepository.UpdateAsync(sport);
                    await auditLogger.log(GetUserId(), $"Edited Sport {id}");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!sportRepository.SportIdExists(sport.SportId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sport);
        }

        // GET: Sports/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            await auditLogger.log(GetUserId(), $"Accessed Delete Sport {id}");
            var sport = await sportRepository.GetByIdAsync(id.Value);

            if (sport == null)
            {
                return NotFound();
            }

            return View(sport);
        }

        // POST: Sports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sport = await sportRepository.GetByIdAsync(id);
            await sportRepository.DeleteAsync(sport);
            await auditLogger.log(GetUserId(), $"Deleted Sport {id}");
            return RedirectToAction(nameof(Index));
        }
        public string GetUserId()
        {
            return User.Claims.FirstOrDefault(c => c.Type == "sub").Value;
        }
    }
}

booking-facilities/Controllers/VenuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using booking_facilities.Models;
using Microsoft.AspNetCore.Authorization;
using X.PagedList;
using booking_facilities.Repositories;
using AberFitnessAuditLogger;

namespace booking_facilities.Controllers
{
    [Authorize(AuthenticationSchemes = "oidc", Policy ="administrator")]
    public class VenuesController : Controller
    {
        private readonly IVenueRepository venueRepository;
        private readonly IAuditLogger auditLogger;

        public VenuesController(IVenueRepository venueRepository, IAuditLogger auditLogger)
        {
            this.venueRepository = venueRepository;
            this.auditLogger = auditLogger;
        }

        // GET: Venues
        public async Task<IActionResult> Index(int? page)
        {
            await auditLogger.log(GetUserId(), "Accessed Venue Index");
            IQueryable<Venue> venues =  venueRepository.GetAllAsync().OrderBy(v => v.VenueName);

            venues = venues.OrderBy(v => v.VenueName);

            var venueList = await venues.ToListAsync();

            var pageNumber = page ?? 1; // if no page was specified in the querystring, default to the first page (1)
            var venuesPerPage = 10;

            var onePageOfVenue = venueList.ToPagedList(pageNumber, venuesPerPage); // will only contain 25 products max because of the pageSize

            ViewBag.onePageOfVenue = onePageOfVenue;
            return View();
        }

        // GET: Venues/Create
        public async Task<IActionResult> Create()
        {
            await auditLogger.log(GetUserId(), "Accessed Create Venue");
            return View();
        }

        // POST: Venues/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VenueId,VenueName")] Venue venue)
        {
            if (venueRepository.DoesVenueExist(venue.VenueName))
            {
                ModelState.AddModelError("VenueName", "Venue already exists. Please enter another venue.");
            }
            else if (ModelState.IsValid)
            {
                venue = await venueRepository.AddAsync(venue);
                await auditLogger.log(GetUserId(), $"Venue Created {venue.VenueName}");
                return RedirectToAction(nameof(Index));
            }
            return View(venue);
        }

        // GET: Venues/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            await auditLogger.log(GetUserId(), $"Venuie Edit Accessed {id}");
            var venue = await venueRepository.GetByIdAsync(id.Value);
            if (venue == null)
            {
                return NotFound();
            }
            return View(venue);
        }

        // POST: Venues/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VenueId,VenueName")] Venue venue)
        {
            if (id != venue.VenueId)
            {
                return NotFound();
            }

            if (venueRepository.DoesVenueExist(venue.VenueName))
            {
                ModelState.AddModelError("VenueName", "Venue already exists. Please enter another venue.");
            }
            else if(ModelState.IsValid)
            {
                try
                {
                    await venueRepository.UpdateAsync(venue);
                    await auditLogger.log(GetUserId(), $"Venuie Edited {venue.VenueName}");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VenueExists(venue.VenueId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(venue);
        }

        // GET: Venues/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            await auditLogger.log(GetUserId(), $"Venuie Delete Accessed {id}");
            var venue = await venueRepository.GetByIdAsync(id.Value);
            if (venue == null)
            {
                return NotFound();
            }

            return View(venue);
        }

        // POST: Venues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var venue = await venueRepository.GetByIdAsync(id);
            await venueRepository.DeleteAsync(venue);
            await auditLogger.log(GetUserId(), $"Venuie Deleted {id}");
            return RedirectToAction(nameof(Index));
        }

        private bool VenueExists(int id)
        {
            return venueRepository.VenueExists(id);
        }
        public string GetUserId()
        {
            return User.Claims.FirstOrDefault(c => c.Type == "sub").Value;
        }
    }
}

booking-facilities/Views/Shared/_BookingScriptsPartial.cshtml
<script type="text/javascript">

    function updateDateTime() {
    document.getElementById("BookingDateTime").value = document.getElementById("BookingDateId").value + "T" + jQuery("#timeDDL :selected").text();
    }

    function updateDateTimeBlock() {
        document.getElementById("BookingDateTime").value = document.getElementById("BookingDateId").value + "T" + jQuery("#timeDDLBlock :selected").text();
        document.getElementById("EndBookingDateTime").value = document.getElementById("EndBookingDateId").value + "T" + jQuery("#endTimeDDL :selected").text();
    }

    function updateSports() {
    document.getElementById("BookingDateId").value = document.getElementById("BookingDateTime").value = "";
    jQuery("#timeDDL").empty();
    urlVenues = '@Url.Content("~/")' + "api/Sports/getSportsByVenue" + '/' + jQuery("#venueDDL").val();


    jQuery.ajax({
        url: urlVenues,
        success: function (json) {

            var items = "";
            jQuery.each(json, function (i, sport) {
                items += "<option value='" + sport.sportId + "'>" + sport.sportName + "</option>";
            })
            jQuery("#sportDDL").empty().html(items);
            updateFacilities();

        }
    });
}

function getTimes() {

    var urlBooking = '@Url.Content("~/")' + "api/booking/" + document.getElementById("BookingDateId").value + "/" + jQuery("#venueDDL").val() + "/" + jQuery("#sportDDL").val();
    jQuery.ajax({
        url: urlBooking,
        success: function (json) {
            var times = "";
            jQuery("#BookingTimeForm").show();

            jQuery.each(json, function (i, time) {
                var dout = new Date(Date.parse(time));
                times += "<option value='" + i + "'>" + ("0" + dout.getHours()).slice(-2) + ":00:00" + "</option>";
            })
            jQuery("#timeDDL").empty().html(times);
            updateDateTime();

        }

    });

}

function populateTimes() {

    var startTime = 9;
    var hoursOpen = 12;

    var startTimes = "";
    var endTimes = "";

    for (i = 0; i < hoursOpen; i++) {

        startTimes += "<option value='" + i + "'>" + ("0" + (i + startTime)).slice(-2) + ":00:00" + "</option>";
        endTimes += "<option value='" + i + "'>" + ("0" + (i + startTime + 1)).slice(-2) + ":00:00" + "</option>";
    }
    jQuery("#timeDDLBlock").empty().html(startTimes);
    jQuery("#endTimeDDL").empty().html(endTimes);

    }


function updateFacilities() {
    urlFacilities = '@Url.Content("~/")' + "api/Facilities/" + jQuery("#venueDDL").val() + "/" + jQuery("#sportDDL").val();
    jQuery.ajax({
        url: urlFacilities,
        success: function (json) {
            var items = "";
            jQuery.each(json, function (i, facility) {
                items += "<option value='" + facility.facilityId + "'>" + facility.facilityName + "</option>";
            })
            jQuery("#facilityDDL").empty().html(items);
        }
    });
    }
</script>

booking-facilities/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - booking-facilities</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Claims.FirstOrDefault(c => c.Type == "user_type").Value.Equals("administrator"))
                    {
                    <li><a asp-area="" asp-controller="Sports" asp-action="Index">Sports</a></li>
                    <li><a asp-area="" asp-controller="Venues" asp-action="Index">Venues</a></li>
                    <li><a asp-area="" asp-controller="Facilities" asp-action="Index">Facilities</a></li>
                    }
                    <li><a asp-area="" asp-controller="Bookings" asp-action="Index">Bookings</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - booking-facilities</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>